/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSymptomsRouteImport } from './routes/_app.symptoms'
import { Route as AppSosRouteImport } from './routes/_app.sos'
import { Route as AppRecordsRouteImport } from './routes/_app.records'
import { Route as AppClinicsRouteImport } from './routes/_app.clinics'
import { Route as AppAppointmentsRouteImport } from './routes/_app.appointments'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomsRoute = AppSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicsRoute = AppClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AppRoute,
} as any)
const AppAppointmentsRoute = AppAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/appointments': typeof AppAppointmentsRoute
  '/clinics': typeof AppClinicsRoute
  '/records': typeof AppRecordsRoute
  '/sos': typeof AppSosRoute
  '/symptoms': typeof AppSymptomsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/appointments': typeof AppAppointmentsRoute
  '/clinics': typeof AppClinicsRoute
  '/records': typeof AppRecordsRoute
  '/sos': typeof AppSosRoute
  '/symptoms': typeof AppSymptomsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/appointments': typeof AppAppointmentsRoute
  '/_app/clinics': typeof AppClinicsRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/sos': typeof AppSosRoute
  '/_app/symptoms': typeof AppSymptomsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/appointments'
    | '/clinics'
    | '/records'
    | '/sos'
    | '/symptoms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/appointments'
    | '/clinics'
    | '/records'
    | '/sos'
    | '/symptoms'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/appointments'
    | '/_app/clinics'
    | '/_app/records'
    | '/_app/sos'
    | '/_app/symptoms'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/symptoms': {
      id: '/_app/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AppSymptomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sos': {
      id: '/_app/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clinics': {
      id: '/_app/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof AppClinicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/appointments': {
      id: '/_app/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppAppointmentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppointmentsRoute: typeof AppAppointmentsRoute
  AppClinicsRoute: typeof AppClinicsRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppSosRoute: typeof AppSosRoute
  AppSymptomsRoute: typeof AppSymptomsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppointmentsRoute: AppAppointmentsRoute,
  AppClinicsRoute: AppClinicsRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppSosRoute: AppSosRoute,
  AppSymptomsRoute: AppSymptomsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
